name: Run React.js

on: 
  push:
    branches:
      - main

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
     
   
      
        

    

    - name: Run React.js
      run: Run React.js
